### ISSUE TITLE
failed make compile in mac

### ISSUE THREAD

**Issue by moonming** [iresty/lua-resty-libr3#5]
cc -O3 -g -Wall -fpic -DBUILDING_SO -c r3_resty.c
cc -shared -fvisibility=hidden r3_resty.o r3/.libs/libr3.a -o libr3.so
Undefined symbols for architecture x86_64:
  "_pcre_compile", referenced from:
      _r3_tree_compile_patterns in libr3.a(node.o)
  "_pcre_exec", referenced from:
      _r3_tree_matchl in libr3.a(node.o)
  "_pcre_free", referenced from:
      _r3_tree_free in libr3.a(node.o)
      _r3_tree_compile_patterns in libr3.a(node.o)
  "_pcre_free_study", referenced from:
      _r3_tree_free in libr3.a(node.o)
      _r3_tree_compile_patterns in libr3.a(node.o)
  "_pcre_study", referenced from:
      _r3_tree_compile_patterns in libr3.a(node.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libr3.so] Error 1

**Comment by membphis** [comment]
fixed already
